server:
  port: 9191

spring:
  application:
    name: public-problem
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: "#Alone117"
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
        port: 8719
      web-context-unify: false
  profiles:
    active: datasource

logging:
  level:
    com.david.open.problem: DEBUG
